"""Terraform Generator Component

Langflow component for generating Terraform HCL code from infrastructure components.
"""

import json
from typing import Optional, Dict, Any, List
from lfx.custom.custom_component.component import Component
from lfx.io import StrInput, DataInput, DropdownInput, Output
from lfx.schema import Data


class TerraformGeneratorComponent(Component):
    """Terraform Code Generator Component
    
    Generates Terraform HCL code from connected infrastructure components.
    """
    
    display_name: str = "Terraform Generator"
    description: str = "Generate Terraform HCL code from infrastructure components"
    documentation: str = "https://www.terraform.io/docs"
    icon: str = "Code"
    priority: int = 50
    name: str = "terraform_generator"
    
    inputs = [
        DataInput(
            name="infrastructure_data",
            display_name="Infrastructure Data",
            info="Infrastructure data from connected components (JSON or dict)",
            required=True
        ),
        DropdownInput(
            name="environment",
            display_name="Environment",
            info="Environment suffix",
            options=["sbx", "live"],
            value="sbx",
            required=True
        ),
        StrInput(
            name="region",
            display_name="AWS Region",
            info="AWS region for resources",
            value="us-east-1",
            required=True
        ),
    ]
    
    outputs = [
        Output(name="terraform_code", display_name="Terraform Code", method="build_terraform"),
        Output(name="variables_tf", display_name="variables.tf", method="build_variables"),
        Output(name="outputs_tf", display_name="outputs.tf", method="build_outputs"),
        Output(name="readme", display_name="README", method="build_readme"),
    ]
    
    def build_terraform(self) -> Data:
        """Generate main.tf Terraform code."""
        try:
            # Parse infrastructure data
            if isinstance(self.infrastructure_data, str):
                infra_data = json.loads(self.infrastructure_data)
            else:
                infra_data = self.infrastructure_data if isinstance(self.infrastructure_data, dict) else {}
            
            suffix = f"-{self.environment}" if self.environment else ""
            
            terraform = f"""# Generated Terraform Configuration
# Environment: {self.environment}
# Region: {self.region}

terraform {{
  required_version = ">= 1.0"
  
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "{self.region}"
}}

"""
            
            # Generate resources based on infrastructure data
            # This is a simplified version - in practice, you'd parse the actual component outputs
            # For now, we'll generate a template structure
            
            terraform += self._generate_resources(infra_data, suffix)
            
            self.status = f"✓ Terraform code generated for {self.environment} environment"
            return Data({'code': terraform, 'filename': 'main.tf'})
            
        except Exception as e:
            error_msg = f"Error generating Terraform: {str(e)}"
            self.status = f"✗ {error_msg}"
            return Data({'error': error_msg})
    
    def build_variables(self) -> Data:
        """Generate variables.tf file."""
        variables = """# Variables for Infrastructure

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "sbx"
}

variable "region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "infrastructure"
}
"""
        return Data({'code': variables, 'filename': 'variables.tf'})
    
    def build_outputs(self) -> Data:
        """Generate outputs.tf file."""
        outputs = f"""# Outputs for Infrastructure

output "region" {{
  description = "AWS region"
  value       = "{self.region}"
}}

output "environment" {{
  description = "Environment"
  value       = "{self.environment}"
}}
"""
        return Data({'code': outputs, 'filename': 'outputs.tf'})
    
    def build_readme(self) -> Data:
        """Generate README.md file."""
        readme = f"""# Terraform Infrastructure

This Terraform configuration was generated by AWS Infrastructure Composer.

## Environment
- **Environment**: {self.environment}
- **Region**: {self.region}

## Usage

1. Initialize Terraform:
```bash
terraform init
```

2. Review the plan:
```bash
terraform plan
```

3. Apply the configuration:
```bash
terraform apply
```

## Generated Resources

This configuration includes:
- VPC and networking resources
- ECS clusters and services
- Load balancers
- Security groups
- IAM roles
- ECR repositories
- Service discovery

## Notes

- All resources are tagged with `ManagedBy: infrastructure-composer`
- Environment suffix: `{self.environment}`
- Make sure to review and customize the configuration before applying
"""
        return Data({'code': readme, 'filename': 'README.md'})
    
    def _generate_resources(self, infra_data: Dict[str, Any], suffix: str) -> str:
        """Generate Terraform resources from infrastructure data."""
        resources = ""
        
        # This is a placeholder - in a real implementation, you would:
        # 1. Parse component outputs from the infrastructure_data
        # 2. Generate appropriate Terraform resources for each component
        # 3. Handle dependencies between resources
        
        # Example: Generate VPC resource if present
        if infra_data.get('vpc'):
            vpc_name = infra_data.get('vpc', {}).get('name', 'main')
            cidr = infra_data.get('vpc', {}).get('cidr_block', '10.0.0.0/16')
            resource_name = vpc_name.lower().replace(' ', '_').replace('-', '_')
            
            resources += f"""
# VPC: {vpc_name}
resource "aws_vpc" "{resource_name}" {{
  cidr_block           = "{cidr}"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {{
    Name        = "{vpc_name}{suffix}"
    Environment = "{self.environment}"
    ManagedBy   = "infrastructure-composer"
  }}
}}

resource "aws_internet_gateway" "{resource_name}_igw" {{
  vpc_id = aws_vpc.{resource_name}.id

  tags = {{
    Name = "{vpc_name}-igw{suffix}"
  }}
}}
"""
        
        # Example: Generate ECS Cluster resource if present
        if infra_data.get('clusters'):
            for cluster in infra_data.get('clusters', []):
                cluster_name = cluster.get('name', 'cluster')
                resource_name = cluster_name.lower().replace(' ', '_').replace('-', '_')
                
                resources += f"""
# ECS Cluster: {cluster_name}
resource "aws_ecs_cluster" "{resource_name}" {{
  name = "{cluster_name}{suffix}"

  setting {{
    name  = "containerInsights"
    value = "enabled"
  }}

  tags = {{
    Name        = "{cluster_name}{suffix}"
    Environment = "{self.environment}"
    ManagedBy   = "infrastructure-composer"
  }}
}}
"""
        
        return resources
